# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.10.0.schema.json

PackageIdentifier: xmn.BetterTrumpet
PackageVersion: 3.0.11
Platform:
- Windows.Desktop
MinimumOSVersion: 10.0.17134.0
InstallerType: inno
Scope: user
InstallModes:
- interactive
- silent
- silentWithProgress
InstallerSwitches:
  Silent: /VERYSILENT /SUPPRESSMSGBOXES /NORESTART /SP-
  SilentWithProgress: /SILENT /SUPPRESSMSGBOXES /NORESTART /SP-
Installers:
- Architecture: x86
  InstallerUrl: https://github.com/xammen/BetterTrumpet/releases/download/v3.0.11/BetterTrumpet-3.0.11-setup.exe
  InstallerSha256: 492D21625FCF44258A93E234606C5DF43F51822D093CA138DC490EE1E8934BB8
ManifestType: installer
ManifestVersion: 1.10.0
ReleaseDate: 2026-04-09
